import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import "../styles/prism.css";

import { ThemeProvider } from "@/context/ThemeProvide";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
//   weight:['100','200','300','400','500','600','700','800']
// });

// const spaceGrotesk = Space_Grotesk({
//   variable: "--font-space",
//   subsets: ["latin"],
//   weight:['300','400','500','600','700']
// });

export const metadata: Metadata = {
  title: "Dev flow App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider
    >
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <ThemeProvider>
          {children}
          <Toaster/>
        </ThemeProvider>
      </body>
    </html>
    </AuthProvider>
  );
}
